import jsPDF from 'jspdf';
import type { Prescription } from './data';

export function generatePrescriptionPDF(prescription: Prescription): void {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 0;

  doc.setFillColor(22, 115, 92);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('CurePath', margin, 18);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text('Digital Prescription', margin, 30);

  y = 55;

  doc.setTextColor(60, 60, 60);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Prescription #${prescription.id.slice(0, 8).toUpperCase()}`, margin, y);
  y += 12;

  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Doctor:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(prescription.doctorName, margin + 22, y);

  doc.setFont('helvetica', 'bold');
  doc.text('Patient:', pageWidth / 2, y);
  doc.setFont('helvetica', 'normal');
  doc.text(prescription.patientName, pageWidth / 2 + 24, y);
  y += 7;

  doc.setFont('helvetica', 'bold');
  doc.text('Date:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date(prescription.createdAt).toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' }), margin + 22, y);

  doc.setFont('helvetica', 'bold');
  doc.text('Status:', pageWidth / 2, y);
  doc.setFont('helvetica', 'normal');
  doc.text(prescription.status.charAt(0).toUpperCase() + prescription.status.slice(1), pageWidth / 2 + 24, y);
  y += 15;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Diagnosis', margin, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(prescription.diagnosis, margin, y);
  y += 15;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Medications', margin, y);
  y += 8;

  const colWidths = [55, 30, 45, 40];
  const headers = ['Name', 'Dosage', 'Frequency', 'Duration'];
  const tableWidth = colWidths.reduce((a, b) => a + b, 0);
  const rowHeight = 8;

  doc.setFillColor(231, 247, 242);
  doc.rect(margin, y - 5, tableWidth, rowHeight, 'F');

  doc.setDrawColor(180, 180, 180);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(40, 40, 40);

  let colX = margin;
  for (let i = 0; i < headers.length; i++) {
    doc.text(headers[i], colX + 2, y);
    colX += colWidths[i];
  }

  doc.line(margin, y + 3, margin + tableWidth, y + 3);
  y += rowHeight;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);

  for (const med of prescription.medications) {
    const values = [med.name, med.dosage, med.frequency, med.duration];
    colX = margin;
    for (let i = 0; i < values.length; i++) {
      doc.text(values[i], colX + 2, y);
      colX += colWidths[i];
    }
    doc.line(margin, y + 3, margin + tableWidth, y + 3);
    y += rowHeight;

    if (med.instructions) {
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      doc.text(`  → ${med.instructions}`, margin + 2, y);
      y += 6;
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
    }
  }

  doc.line(margin, y - rowHeight + 3, margin, y - rowHeight + 3 - (prescription.medications.length * rowHeight) - rowHeight);
  doc.line(margin + tableWidth, y - rowHeight + 3, margin + tableWidth, y - rowHeight + 3 - (prescription.medications.length * rowHeight) - rowHeight);

  y += 10;

  if (prescription.notes) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(40, 40, 40);
    doc.text('Notes', margin, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    const noteLines = doc.splitTextToSize(prescription.notes, pageWidth - margin * 2);
    doc.text(noteLines, margin, y);
    y += noteLines.length * 5 + 10;
  }

  y = Math.max(y + 10, 220);

  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 15;

  doc.setDrawColor(60, 60, 60);
  doc.line(margin, y + 5, margin + 60, y + 5);
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text("Doctor's Signature", margin, y + 12);

  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by CurePath', pageWidth / 2, footerY, { align: 'center' });

  doc.save(`prescription-${prescription.id.slice(0, 8)}.pdf`);
}
